version: '3.7'

services: 
    frontend:
        stdin_open: true
        build: 
            target: development
            context: ./frontend
            dockerfile: Dockerfile
        volumes: 
            - ./frontend:/app
        entrypoint: ["yarn", "test", "--watchAll=false"]
    api:
        build:
            target: development
            context: ./api
            dockerfile: Dockerfile
        volumes: 
            - ./api:/app  
        entrypoint: ["python", "-m", "pytest"]
