#!/usr/bin/env bash

ACTION=$1
shift

shopt -s nocasematch
case $ACTION in
test)
    CMD="docker-compose -f docker-compose.yml -f docker-compose.test.yml up"
    ;;
production)
    CMD="docker-compose -f docker-compose.yml -f docker-compose.production.yml up"
    ;;
dev|development|*)
    CMD="docker-compose up"
    ;;
esac

eval "${CMD} ${@}"
